server {
    listen 80;
    server_name ВАШ_IP_ИЛИ_ДОМЕН;

    # Увеличиваем таймаут для больших запросов (CSV выгрузка)
    proxy_read_timeout 120s;
    proxy_connect_timeout 10s;

    location / {
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
