// api/index.js — Vercel Serverless Function
// Works with pre-aggregated JSON files (generated by aggregate_csv.py).
// Memory usage: ~20-50 MB instead of 500+ MB for raw CSV.
//
// GitHub Release structure:
//   Tag: data-2025  →  file: 2025_agg.json
//   Tag: data-2026  →  file: 2026_agg.json
//
// Required env vars in Vercel:
//   GITHUB_OWNER  — GitHub username
//   GITHUB_REPO   — repository name
//   GITHUB_TOKEN  — personal access token (public_repo scope)

export const config = { maxDuration: 30 };

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { start, end, compStart, compEnd, omsuFilter = [], sourceFilter = [], exportRaw = false } = req.body;
    if (!start || !end || !compStart || !compEnd) {
      return res.status(400).json({ error: 'Заполните все 4 поля с датами' });
    }

    const OWNER = process.env.GITHUB_OWNER;
    const REPO  = process.env.GITHUB_REPO;
    const TOKEN = process.env.GITHUB_TOKEN;
    if (!OWNER || !REPO) {
      return res.status(500).json({ error: 'GITHUB_OWNER и GITHUB_REPO не настроены' });
    }

    const aggUrl = (year) =>
      `https://github.com/${OWNER}/${REPO}/releases/download/data-${year}/${year}_agg.json`;

    // Which years do we need?
    const yearsNeeded = new Set();
    const addYears = (s, e) => {
      for (let y = +s.slice(0,4); y <= +e.slice(0,4); y++) yearsNeeded.add(y);
    };
    addYears(start, end);
    addYears(compStart, compEnd);

    // Load all needed JSON aggregates in parallel
    const yearAgg = {};
    await Promise.all([...yearsNeeded].map(async (year) => {
      const url = aggUrl(year);
      const headers = TOKEN
        ? { Authorization: `token ${TOKEN}`, Accept: 'application/octet-stream' }
        : { Accept: 'application/octet-stream' };
      const resp = await fetch(url, { headers, redirect: 'follow' });
      if (!resp.ok) {
        if (resp.status === 404) { console.warn(`${year}_agg.json not found`); yearAgg[year] = {}; return; }
        throw new Error(`Ошибка загрузки ${year}_agg.json: ${resp.status}`);
      }
      yearAgg[year] = await resp.json();
      console.log(`Loaded ${year}_agg.json: ${Object.keys(yearAgg[year]).length} days`);
    }));

    // ── CSV export mode: stream gzip → filter → write CSV directly to response ──
    // True streaming: never accumulates rows in RAM, works for any period size.
    if (exportRaw) {
      const rowsUrl = (year) =>
        `https://github.com/${OWNER}/${REPO}/releases/download/data-${year}/${year}_rows.jsonl.gz`;

      const COLS = [
        'Порядковый номер','Номер ЕЦУР','Номер в источнике',
        'Дата (первого взятия в работу)','Направление','Синт. группа',
        'Факт','Подтема','Статус','Куратор','Исполнитель','ОМСУ',
        'Источник','Спам (да/нет)','Тип сообщения - 0 проблемы, 1 - предложения',
        'Описание','Почта заявителя','Управляющая компания','Адрес',
        'Район','Населенный пункт','Улица','Дом','Внутренний Id'
      ];

      const escCsv = (v) => {
        const s = String(v ?? '');
        return (s.includes(';') || s.includes('"') || s.includes('\n') || s.includes('\r'))
          ? '"' + s.replace(/"/g, '""') + '"'
          : s;
      };

      // Set streaming CSV response headers
      const fname = `export_${start}_${end}.csv`;
      res.setHeader('Content-Type', 'text/csv; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${fname}"`);
      res.setHeader('Transfer-Encoding', 'chunked');
      res.setHeader('X-Content-Type-Options', 'nosniff');

      // Write UTF-8 BOM so Excel opens Cyrillic correctly
      res.write('\uFEFF');
      // Write header row
      res.write(COLS.map(escCsv).join(';') + '\r\n');

      let totalRows = 0;

      for (const year of [...yearsNeeded].sort()) {
        const url = rowsUrl(year);
        const hdrs = TOKEN
          ? { Authorization: `token ${TOKEN}`, Accept: 'application/octet-stream' }
          : { Accept: 'application/octet-stream' };

        const resp2 = await fetch(url, { headers: hdrs, redirect: 'follow' });
        if (!resp2.ok) {
          console.warn(`${year}_rows.jsonl.gz not found`);
          continue;
        }

        // Stream: decompress → filter → write CSV lines directly
        const count = await streamJsonlGzToCsv(resp2, start, end, omsuFilter, sourceFilter, COLS, escCsv, res);
        totalRows += count;
        console.log(`CSV export ${year}: ${count} rows written`);
      }

      console.log(`CSV export total: ${totalRows} rows`);
      res.end();
      return;
    }

    // Merge all years into one flat { date -> { sg -> groupData } }
    const allDays = {};
    for (const agg of Object.values(yearAgg)) {
      for (const [date, groups] of Object.entries(agg)) {
        allDays[date] = allDays[date] || {};
        for (const [sg, g] of Object.entries(groups)) {
          if (!allDays[date][sg]) {
            allDays[date][sg] = g;
          } else {
            mergeGroup(allDays[date][sg], g);
          }
        }
      }
    }

    // Build aggregates for main and comparison periods
    const mainAgg  = buildPeriodAgg(allDays, start,     end,     omsuFilter, sourceFilter);
    const compAgg  = buildPeriodAgg(allDays, compStart, compEnd, omsuFilter, sourceFilter);
    const daily    = buildDaily(allDays, start, end, omsuFilter, sourceFilter);

    const data = processDashboardData(mainAgg.groups, compAgg.groups);

    const dailyComp = buildDaily(allDays, compStart, compEnd, omsuFilter, sourceFilter);

    return res.status(200).json({
      data,
      daily,
      dailyComp,
      yearsLoaded: [...yearsNeeded],
      counts: { main: mainAgg.total, comp: compAgg.total }
    });

  } catch (err) {
    console.error('API Error:', err);
    return res.status(500).json({ error: err.message || 'Внутренняя ошибка сервера' });
  }
}

// ─── Merge two group objects in place ───
function mergeGroup(dst, src) {
  dst.total = (dst.total || 0) + (src.total || 0);
  // subs
  for (const [k, v] of Object.entries(src.subs || {})) {
    if (!dst.subs[k]) dst.subs[k] = { count: 0, facts: {} };
    dst.subs[k].count += v.count || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.subs[k].facts[f] = (dst.subs[k].facts[f] || 0) + n;
    }
  }
  // omsu
  for (const [k, v] of Object.entries(src.omsu || {})) {
    if (!dst.omsu[k]) dst.omsu[k] = { c: 0, subs: {} };
    dst.omsu[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.omsu[k].subs[s] = (dst.omsu[k].subs[s] || 0) + n;
    }
  }
  // facts
  for (const [k, n] of Object.entries(src.facts || {})) {
    dst.facts[k] = (dst.facts[k] || 0) + n;
  }
  // mails
  for (const [k, v] of Object.entries(src.mails || {})) {
    if (!dst.mails[k]) dst.mails[k] = { c: 0, facts: {}, omsus: [] };
    dst.mails[k].c += v.c || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.mails[k].facts[f] = (dst.mails[k].facts[f] || 0) + n;
    }
    const existing = new Set(dst.mails[k].omsus);
    for (const o of (v.omsus || [])) existing.add(o);
    dst.mails[k].omsus = [...existing];
  }
  // addrs
  for (const [k, v] of Object.entries(src.addrs || {})) {
    if (!dst.addrs[k]) dst.addrs[k] = { c: 0, subs: {} };
    dst.addrs[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.addrs[k].subs[s] = (dst.addrs[k].subs[s] || 0) + n;
    }
  }
}

// ─── Aggregate days in a date range into group totals ───
function buildPeriodAgg(allDays, start, end, omsuFilter, sourceFilter = []) {
  const groups = {};
  let total = 0;

  for (const [date, dayGroups] of Object.entries(allDays)) {
    if (date < start || date > end) continue;

    for (const [sg, g] of Object.entries(dayGroups)) {
      // Source filter: check if any rows from selected sources exist in this group/day
      if (sourceFilter.length > 0) {
        const srcTotal = sourceFilter.reduce((sum, s) => sum + (g.sources?.[s] || 0), 0);
        if (srcTotal === 0) continue;
      }

      if (!groups[sg]) groups[sg] = { total:0, subs:{}, omsu:{}, facts:{}, mails:{}, addrs:{} };
      const dst = groups[sg];

      if (omsuFilter.length === 0 && sourceFilter.length === 0) {
        // No filters — merge whole group
        addToGroup(dst, g);
        total += g.total || 0;
      } else if (omsuFilter.length === 0 && sourceFilter.length > 0) {
        // Source filter only — scale group by source ratio
        const srcTotal = sourceFilter.reduce((sum, s) => sum + (g.sources?.[s] || 0), 0);
        const ratio = (g.total || 1) > 0 ? srcTotal / g.total : 0;
        if (ratio > 0) {
          addToGroupScaled(dst, g, ratio);
          total += srcTotal;
        }
      } else {
        // Filter by OMSU — only count rows from selected OMSU
        let groupTotal = 0;
        for (const omsu of omsuFilter) {
          const od = g.omsu?.[omsu];
          if (!od) continue;
          groupTotal += od.c || 0;
          if (!dst.omsu[omsu]) dst.omsu[omsu] = { c: 0, subs: {} };
          dst.omsu[omsu].c += od.c || 0;
          for (const [s, n] of Object.entries(od.subs || {})) {
            dst.omsu[omsu].subs[s] = (dst.omsu[omsu].subs[s] || 0) + n;
            // Add to subs
            if (!dst.subs[s]) dst.subs[s] = { count: 0, facts: {} };
            dst.subs[s].count += n;
            // Facts for this sub — proportional from day's sub facts
            const subTotal = g.subs?.[s]?.count || 1;
            const ratio = n / subTotal;
            for (const [f, fn] of Object.entries(g.subs?.[s]?.facts || {})) {
              dst.subs[s].facts[f] = (dst.subs[s].facts[f] || 0) + Math.round(fn * ratio);
              dst.facts[f] = (dst.facts[f] || 0) + Math.round(fn * ratio);
            }
          }
        }
        dst.total += groupTotal;
        total += groupTotal;
        // Add mails — include if any of mail's omsus match the filter
        for (const [mail, md] of Object.entries(g.mails || {})) {
          const mailOmsus = (md.omsus || []).filter(o => omsuFilter.includes(o));
          if (mailOmsus.length === 0) continue;
          if (!dst.mails[mail]) dst.mails[mail] = { c: 0, facts: {}, omsus: [] };
          dst.mails[mail].c += md.c || 0;
          for (const [f, n] of Object.entries(md.facts || {}))
            dst.mails[mail].facts[f] = (dst.mails[mail].facts[f] || 0) + n;
          const exM = new Set(dst.mails[mail].omsus);
          for (const o of mailOmsus) exM.add(o);
          dst.mails[mail].omsus = [...exM];
        }
      }
    }
  }

  return { groups, total };
}

function addToGroup(dst, g) {
  dst.total += g.total || 0;
  for (const [k, v] of Object.entries(g.subs || {})) {
    if (!dst.subs[k]) dst.subs[k] = { count: 0, facts: {} };
    dst.subs[k].count += v.count || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.subs[k].facts[f] = (dst.subs[k].facts[f] || 0) + n;
    }
  }
  for (const [k, v] of Object.entries(g.omsu || {})) {
    if (!dst.omsu[k]) dst.omsu[k] = { c: 0, subs: {} };
    dst.omsu[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.omsu[k].subs[s] = (dst.omsu[k].subs[s] || 0) + n;
    }
  }
  for (const [k, n] of Object.entries(g.facts || {})) {
    dst.facts[k] = (dst.facts[k] || 0) + n;
  }
  for (const [k, v] of Object.entries(g.mails || {})) {
    if (!dst.mails[k]) dst.mails[k] = { c: 0, facts: {}, omsus: [] };
    dst.mails[k].c += v.c || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.mails[k].facts[f] = (dst.mails[k].facts[f] || 0) + n;
    }
    const ex = new Set(dst.mails[k].omsus);
    for (const o of (v.omsus || [])) ex.add(o);
    dst.mails[k].omsus = [...ex];
  }
  for (const [k, v] of Object.entries(g.addrs || {})) {
    if (!dst.addrs[k]) dst.addrs[k] = { c: 0, subs: {} };
    dst.addrs[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.addrs[k].subs[s] = (dst.addrs[k].subs[s] || 0) + n;
    }
  }
}

// ─── Scale group values by ratio (used when sourceFilter applied without omsuFilter) ───
function addToGroupScaled(dst, g, ratio) {
  const sc = v => Math.max(1, Math.round(v * ratio));
  dst.total += Math.round((g.total || 0) * ratio);
  for (const [k, v] of Object.entries(g.subs || {})) {
    if (!dst.subs[k]) dst.subs[k] = { count: 0, facts: {} };
    dst.subs[k].count += sc(v.count || 0);
    for (const [f, n] of Object.entries(v.facts || {}))
      dst.subs[k].facts[f] = (dst.subs[k].facts[f] || 0) + sc(n);
  }
  for (const [k, v] of Object.entries(g.omsu || {})) {
    if (!dst.omsu[k]) dst.omsu[k] = { c: 0, subs: {} };
    dst.omsu[k].c += sc(v.c || 0);
    for (const [s, n] of Object.entries(v.subs || {}))
      dst.omsu[k].subs[s] = (dst.omsu[k].subs[s] || 0) + sc(n);
  }
  for (const [k, n] of Object.entries(g.facts || {}))
    dst.facts[k] = (dst.facts[k] || 0) + sc(n);
  for (const [k, v] of Object.entries(g.mails || {})) {
    if (!dst.mails[k]) dst.mails[k] = { c: 0, facts: {}, omsus: [] };
    dst.mails[k].c += sc(v.c || 0);
    for (const [f, n] of Object.entries(v.facts || {}))
      dst.mails[k].facts[f] = (dst.mails[k].facts[f] || 0) + sc(n);
    // preserve omsus tags
    const exS = new Set(dst.mails[k].omsus);
    for (const o of (v.omsus || [])) exS.add(o);
    dst.mails[k].omsus = [...exS];
  }
  for (const [k, v] of Object.entries(g.addrs || {})) {
    if (!dst.addrs[k]) dst.addrs[k] = { c: 0, subs: {} };
    dst.addrs[k].c += sc(v.c || 0);
    for (const [s, n] of Object.entries(v.subs || {}))
      dst.addrs[k].subs[s] = (dst.addrs[k].subs[s] || 0) + sc(n);
  }
}

// ─── Daily counts for sparkline ───
function buildDaily(allDays, start, end, omsuFilter, sourceFilter = []) {
  const daily = {};
  for (const [date, groups] of Object.entries(allDays)) {
    if (date < start || date > end) continue;
    daily[date] = {};
    for (const [sg, g] of Object.entries(groups)) {
      let n = 0;
      if (omsuFilter.length === 0 && sourceFilter.length === 0) {
        n = g.total || 0;
      } else if (omsuFilter.length > 0) {
        for (const omsu of omsuFilter) n += g.omsu?.[omsu]?.c || 0;
      } else if (sourceFilter.length > 0) {
        for (const src of sourceFilter) n += g.sources?.[src] || 0;
      }
      if (n > 0) daily[date][sg] = (daily[date][sg] || 0) + n;
    }
  }
  return daily;
}

// ─── Build dashboard data from aggregated groups ───
function processDashboardData(main, comp) {
  const result = [];
  const dyn = (v, cv) => {
    const d = v - cv;
    return { pct: cv === 0 ? (v > 0 ? 100 : 0) : Math.round((d/cv)*100), abs: d };
  };

  for (const [name, m] of Object.entries(main)) {
    const c = comp[name] || { total:0, subs:{}, omsu:{}, facts:{}, mails:{}, addrs:{} };
    const entry = { name, total: m.total, compTotal: c.total, subs:[], facts:[], omsus:[], mails:[], addrs:[] };

    Object.entries(m.subs).sort((a,b)=>b[1].count-a[1].count).forEach(([k,v]) => {
      const {pct,abs} = dyn(v.count, c.subs[k]?.count||0);
      entry.subs.push({ name:k, count:v.count, pctGroup:Math.round((v.count/m.total)*100), dynPct:pct, dynAbs:abs,
        facts: Object.entries(v.facts||{}).sort((a,b)=>b[1]-a[1]) });
    });
    Object.entries(m.facts).sort((a,b)=>b[1]-a[1]).forEach(([k,v]) => {
      const {pct,abs} = dyn(v, c.facts[k]||0);
      entry.facts.push({ name:k, count:v, dynPct:pct, dynAbs:abs });
    });
    Object.entries(m.omsu).sort((a,b)=>b[1].c-a[1].c).forEach(([k,d]) => {
      const {pct,abs} = dyn(d.c, c.omsu[k]?.c||0);
      const ss = Object.entries(d.subs||{}).sort((a,b)=>b[1]-a[1]);
      entry.omsus.push({ name:k, count:d.c, dynPct:pct, dynAbs:abs,
        mainSub:ss[0]?.[0]||'-', mainSubCnt:ss[0]?.[1]||0,
        mainSubPct: d.c>0 ? Math.round((ss[0]?.[1]||0)/d.c*100) : 0 });
    });
    Object.entries(m.mails||{}).sort((a,b)=>b[1].c-a[1].c).forEach(([k,d]) => {
      entry.mails.push({ email:k, count:d.c, facts:Object.entries(d.facts||{}).sort((a,b)=>b[1]-a[1]), omsus:d.omsus||[] });
    });
    Object.entries(m.addrs||{}).sort((a,b)=>b[1].c-a[1].c).forEach(([k,d]) => {
      const ss = Object.entries(d.subs||{}).sort((a,b)=>b[1]-a[1]);
      entry.addrs.push({ address:k, count:d.c, mainSub:ss[0]?.[0]||'-',
        mainSubCnt:ss[0]?.[1]||0, mainSubPct: d.c>0?Math.round((ss[0]?.[1]||0)/d.c*100):0 });
    });
    result.push(entry);
  }
  return result.sort((a,b)=>b.total-a.total);
}

// ─── Date parser (used by buildRawRows) ───
function parseDate(val) {
  if (!val) return null;
  const s = String(val).trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  const m = s.match(/^(\d{2})\.(\d{2})\.(\d{4})/);
  if (m) return `${m[3]}-${m[2]}-${m[1]}`;
  const d = new Date(s);
  return isNaN(d) ? null : d.toISOString().slice(0, 10);
}


// ─── CSV Parser (handles semicolon/comma delimiter, quoted multiline fields) ───
function parseCSV(text) {
  const rows = [];
  let headers = null, colIdx = {}, delim = ';';
  let inQ = false, field = '', fields = [];

  const commitField = () => { fields.push(inQ ? field : field.trim()); field = ''; inQ = false; };
  const commitRow = () => {
    const row = fields; fields = [];
    if (!row.length || (row.length === 1 && !row[0])) return;
    if (!headers) {
      if (row.length === 1 && row[0].includes(',')) {
        delim = ',';
        headers = row[0].split(',').map(h => h.replace(/^\uFEFF/, '').trim());
      } else {
        headers = row.map(h => h.replace(/^\uFEFF/, '').trim());
      }
      headers.forEach((h, i) => colIdx[h] = i);
      return;
    }
    const obj = {};
    headers.forEach((h, i) => obj[h] = (row[i] || '').trim());
    rows.push(obj);
  };

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQ) {
      if (ch === '"') { if (text[i+1] === '"') { field += '"'; i++; } else inQ = false; }
      else field += ch;
    } else {
      if (ch === '"' && field === '') inQ = true;
      else if (ch === delim) commitField();
      else if (ch === '\n') { commitField(); commitRow(); }
      else if (ch === '\r') {}
      else field += ch;
    }
  }
  if (field || fields.length) { commitField(); commitRow(); }
  return rows;
}


// ─── Stream gzip JSONL → filter → write CSV lines to response (zero RAM accumulation) ───
async function streamJsonlGzToCsv(response, start, end, omsuFilter, sourceFilter, cols, escCsv, res) {
  const { createGunzip } = await import('node:zlib');

  return new Promise((resolve, reject) => {
    let count = 0;
    const gunzip = createGunzip();
    let buf = '';

    gunzip.on('data', chunk => {
      buf += chunk.toString('utf-8');
      const lines = buf.split('\n');
      buf = lines.pop();
      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const row = JSON.parse(line);
          const date = (row['Дата (первого взятия в работу)'] || '').slice(0, 10);
          if (!date || date < start || date > end) continue;
          if (omsuFilter.length > 0 && !omsuFilter.includes((row['ОМСУ'] || '').trim())) continue;
          if (sourceFilter.length > 0 && !sourceFilter.includes((row['Источник'] || '').trim())) continue;
          res.write(cols.map(c => escCsv(row[c])).join(';') + '\r\n');
          count++;
        } catch (_) {}
      }
    });

    gunzip.on('end', () => {
      if (buf.trim()) {
        try {
          const row = JSON.parse(buf);
          const date = (row['Дата (первого взятия в работу)'] || '').slice(0, 10);
          if (date && date >= start && date <= end) {
            const omsuOk = omsuFilter.length === 0 || omsuFilter.includes((row['ОМСУ'] || '').trim());
            const srcOk  = sourceFilter.length === 0 || sourceFilter.includes((row['Источник'] || '').trim());
            if (omsuOk && srcOk) {
              res.write(cols.map(c => escCsv(row[c])).join(';') + '\r\n');
              count++;
            }
          }
        } catch (_) {}
      }
      resolve(count);
    });

    gunzip.on('error', reject);

    const reader = response.body.getReader();
    (async () => {
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) { gunzip.end(); break; }
          gunzip.write(Buffer.from(value));
        }
      } catch (e) { reject(e); }
    })();
  });
}

// ─── Decompress gzip JSONL stream, filter rows by date/omsu, return array ───
// Processes data line-by-line: never loads the entire file into RAM.
async function decompressJsonlGz(response, start, end, omsuFilter) {
  const { createGunzip } = await import('node:zlib');

  return new Promise((resolve, reject) => {
    const results = [];
    const gunzip = createGunzip();
    let buf = '';

    gunzip.on('data', chunk => {
      buf += chunk.toString('utf-8');
      const lines = buf.split('\n');
      buf = lines.pop(); // keep incomplete trailing line
      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const row = JSON.parse(line);
          const date = (row['Дата (первого взятия в работу)'] || '').slice(0, 10);
          if (!date || date < start || date > end) continue;
          if (omsuFilter.length > 0 && !omsuFilter.includes((row['ОМСУ'] || '').trim())) continue;
          results.push(row);
        } catch (_) {}
      }
    });

    gunzip.on('end', () => {
      // flush last line if file doesn't end with \n
      if (buf.trim()) {
        try {
          const row = JSON.parse(buf);
          const date = (row['Дата (первого взятия в работу)'] || '').slice(0, 10);
          if (date && date >= start && date <= end) {
            if (omsuFilter.length === 0 || omsuFilter.includes((row['ОМСУ'] || '').trim()))
              results.push(row);
          }
        } catch (_) {}
      }
      resolve(results);
    });

    gunzip.on('error', reject);

    // Pipe fetch response body → gunzip
    const reader = response.body.getReader();
    (async () => {
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) { gunzip.end(); break; }
          gunzip.write(Buffer.from(value));
        }
      } catch (e) { reject(e); }
    })();
  });
}
