// api/index.js — Vercel Serverless Function
// Works with pre-aggregated JSON files (generated by aggregate_csv.py).
// Memory usage: ~20-50 MB instead of 500+ MB for raw CSV.
//
// GitHub Release structure:
//   Tag: data-2025  →  file: 2025_agg.json
//   Tag: data-2026  →  file: 2026_agg.json
//
// Required env vars in Vercel:
//   GITHUB_OWNER  — GitHub username
//   GITHUB_REPO   — repository name
//   GITHUB_TOKEN  — personal access token (public_repo scope)

export const config = { maxDuration: 30 };

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { start, end, compStart, compEnd, omsuFilter = [] } = req.body;
    if (!start || !end || !compStart || !compEnd) {
      return res.status(400).json({ error: 'Заполните все 4 поля с датами' });
    }

    const OWNER = process.env.GITHUB_OWNER;
    const REPO  = process.env.GITHUB_REPO;
    const TOKEN = process.env.GITHUB_TOKEN;
    if (!OWNER || !REPO) {
      return res.status(500).json({ error: 'GITHUB_OWNER и GITHUB_REPO не настроены' });
    }

    const aggUrl = (year) =>
      `https://github.com/${OWNER}/${REPO}/releases/download/data-${year}/${year}_agg.json`;

    // Which years do we need?
    const yearsNeeded = new Set();
    const addYears = (s, e) => {
      for (let y = +s.slice(0,4); y <= +e.slice(0,4); y++) yearsNeeded.add(y);
    };
    addYears(start, end);
    addYears(compStart, compEnd);

    // Load all needed JSON aggregates in parallel
    const yearAgg = {};
    await Promise.all([...yearsNeeded].map(async (year) => {
      const url = aggUrl(year);
      const headers = TOKEN
        ? { Authorization: `token ${TOKEN}`, Accept: 'application/octet-stream' }
        : { Accept: 'application/octet-stream' };
      const resp = await fetch(url, { headers, redirect: 'follow' });
      if (!resp.ok) {
        if (resp.status === 404) { console.warn(`${year}_agg.json not found`); yearAgg[year] = {}; return; }
        throw new Error(`Ошибка загрузки ${year}_agg.json: ${resp.status}`);
      }
      yearAgg[year] = await resp.json();
      console.log(`Loaded ${year}_agg.json: ${Object.keys(yearAgg[year]).length} days`);
    }));

    // Merge all years into one flat { date -> { sg -> groupData } }
    const allDays = {};
    for (const agg of Object.values(yearAgg)) {
      for (const [date, groups] of Object.entries(agg)) {
        allDays[date] = allDays[date] || {};
        for (const [sg, g] of Object.entries(groups)) {
          if (!allDays[date][sg]) {
            allDays[date][sg] = g;
          } else {
            mergeGroup(allDays[date][sg], g);
          }
        }
      }
    }

    // Build aggregates for main and comparison periods
    const mainAgg  = buildPeriodAgg(allDays, start,     end,     omsuFilter);
    const compAgg  = buildPeriodAgg(allDays, compStart, compEnd, omsuFilter);
    const daily    = buildDaily(allDays, start, end, omsuFilter);

    const data = processDashboardData(mainAgg.groups, compAgg.groups);

    return res.status(200).json({
      data,
      daily,
      yearsLoaded: [...yearsNeeded],
      counts: { main: mainAgg.total, comp: compAgg.total }
    });

  } catch (err) {
    console.error('API Error:', err);
    return res.status(500).json({ error: err.message || 'Внутренняя ошибка сервера' });
  }
}

// ─── Merge two group objects in place ───
function mergeGroup(dst, src) {
  dst.total = (dst.total || 0) + (src.total || 0);
  // subs
  for (const [k, v] of Object.entries(src.subs || {})) {
    if (!dst.subs[k]) dst.subs[k] = { count: 0, facts: {} };
    dst.subs[k].count += v.count || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.subs[k].facts[f] = (dst.subs[k].facts[f] || 0) + n;
    }
  }
  // omsu
  for (const [k, v] of Object.entries(src.omsu || {})) {
    if (!dst.omsu[k]) dst.omsu[k] = { c: 0, subs: {} };
    dst.omsu[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.omsu[k].subs[s] = (dst.omsu[k].subs[s] || 0) + n;
    }
  }
  // facts
  for (const [k, n] of Object.entries(src.facts || {})) {
    dst.facts[k] = (dst.facts[k] || 0) + n;
  }
  // mails
  for (const [k, v] of Object.entries(src.mails || {})) {
    if (!dst.mails[k]) dst.mails[k] = { c: 0, facts: {}, omsus: [] };
    dst.mails[k].c += v.c || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.mails[k].facts[f] = (dst.mails[k].facts[f] || 0) + n;
    }
    const existing = new Set(dst.mails[k].omsus);
    for (const o of (v.omsus || [])) existing.add(o);
    dst.mails[k].omsus = [...existing];
  }
  // addrs
  for (const [k, v] of Object.entries(src.addrs || {})) {
    if (!dst.addrs[k]) dst.addrs[k] = { c: 0, subs: {} };
    dst.addrs[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.addrs[k].subs[s] = (dst.addrs[k].subs[s] || 0) + n;
    }
  }
}

// ─── Aggregate days in a date range into group totals ───
function buildPeriodAgg(allDays, start, end, omsuFilter) {
  const groups = {};
  let total = 0;

  for (const [date, dayGroups] of Object.entries(allDays)) {
    if (date < start || date > end) continue;

    for (const [sg, g] of Object.entries(dayGroups)) {
      if (!groups[sg]) groups[sg] = { total:0, subs:{}, omsu:{}, facts:{}, mails:{}, addrs:{} };
      const dst = groups[sg];

      if (omsuFilter.length === 0) {
        // No filter — merge whole group
        addToGroup(dst, g);
        total += g.total || 0;
      } else {
        // Filter by OMSU — only count rows from selected OMSU
        let groupTotal = 0;
        for (const omsu of omsuFilter) {
          const od = g.omsu?.[omsu];
          if (!od) continue;
          groupTotal += od.c || 0;
          if (!dst.omsu[omsu]) dst.omsu[omsu] = { c: 0, subs: {} };
          dst.omsu[omsu].c += od.c || 0;
          for (const [s, n] of Object.entries(od.subs || {})) {
            dst.omsu[omsu].subs[s] = (dst.omsu[omsu].subs[s] || 0) + n;
            // Add to subs
            if (!dst.subs[s]) dst.subs[s] = { count: 0, facts: {} };
            dst.subs[s].count += n;
            // Facts for this sub — proportional from day's sub facts
            const subTotal = g.subs?.[s]?.count || 1;
            const ratio = n / subTotal;
            for (const [f, fn] of Object.entries(g.subs?.[s]?.facts || {})) {
              dst.subs[s].facts[f] = (dst.subs[s].facts[f] || 0) + Math.round(fn * ratio);
              dst.facts[f] = (dst.facts[f] || 0) + Math.round(fn * ratio);
            }
          }
        }
        dst.total += groupTotal;
        total += groupTotal;
      }
    }
  }

  return { groups, total };
}

function addToGroup(dst, g) {
  dst.total += g.total || 0;
  for (const [k, v] of Object.entries(g.subs || {})) {
    if (!dst.subs[k]) dst.subs[k] = { count: 0, facts: {} };
    dst.subs[k].count += v.count || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.subs[k].facts[f] = (dst.subs[k].facts[f] || 0) + n;
    }
  }
  for (const [k, v] of Object.entries(g.omsu || {})) {
    if (!dst.omsu[k]) dst.omsu[k] = { c: 0, subs: {} };
    dst.omsu[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.omsu[k].subs[s] = (dst.omsu[k].subs[s] || 0) + n;
    }
  }
  for (const [k, n] of Object.entries(g.facts || {})) {
    dst.facts[k] = (dst.facts[k] || 0) + n;
  }
  for (const [k, v] of Object.entries(g.mails || {})) {
    if (!dst.mails[k]) dst.mails[k] = { c: 0, facts: {}, omsus: [] };
    dst.mails[k].c += v.c || 0;
    for (const [f, n] of Object.entries(v.facts || {})) {
      dst.mails[k].facts[f] = (dst.mails[k].facts[f] || 0) + n;
    }
    const ex = new Set(dst.mails[k].omsus);
    for (const o of (v.omsus || [])) ex.add(o);
    dst.mails[k].omsus = [...ex];
  }
  for (const [k, v] of Object.entries(g.addrs || {})) {
    if (!dst.addrs[k]) dst.addrs[k] = { c: 0, subs: {} };
    dst.addrs[k].c += v.c || 0;
    for (const [s, n] of Object.entries(v.subs || {})) {
      dst.addrs[k].subs[s] = (dst.addrs[k].subs[s] || 0) + n;
    }
  }
}

// ─── Daily counts for sparkline ───
function buildDaily(allDays, start, end, omsuFilter) {
  const daily = {};
  for (const [date, groups] of Object.entries(allDays)) {
    if (date < start || date > end) continue;
    daily[date] = {};
    for (const [sg, g] of Object.entries(groups)) {
      if (omsuFilter.length === 0) {
        daily[date][sg] = (daily[date][sg] || 0) + (g.total || 0);
      } else {
        let n = 0;
        for (const omsu of omsuFilter) n += g.omsu?.[omsu]?.c || 0;
        if (n > 0) daily[date][sg] = (daily[date][sg] || 0) + n;
      }
    }
  }
  return daily;
}

// ─── Build dashboard data from aggregated groups ───
function processDashboardData(main, comp) {
  const result = [];
  const dyn = (v, cv) => {
    const d = v - cv;
    return { pct: cv === 0 ? (v > 0 ? 100 : 0) : Math.round((d/cv)*100), abs: d };
  };

  for (const [name, m] of Object.entries(main)) {
    const c = comp[name] || { total:0, subs:{}, omsu:{}, facts:{}, mails:{}, addrs:{} };
    const entry = { name, total: m.total, compTotal: c.total, subs:[], facts:[], omsus:[], mails:[], addrs:[] };

    Object.entries(m.subs).sort((a,b)=>b[1].count-a[1].count).forEach(([k,v]) => {
      const {pct,abs} = dyn(v.count, c.subs[k]?.count||0);
      entry.subs.push({ name:k, count:v.count, pctGroup:Math.round((v.count/m.total)*100), dynPct:pct, dynAbs:abs,
        facts: Object.entries(v.facts||{}).sort((a,b)=>b[1]-a[1]) });
    });
    Object.entries(m.facts).sort((a,b)=>b[1]-a[1]).forEach(([k,v]) => {
      const {pct,abs} = dyn(v, c.facts[k]||0);
      entry.facts.push({ name:k, count:v, dynPct:pct, dynAbs:abs });
    });
    Object.entries(m.omsu).sort((a,b)=>b[1].c-a[1].c).forEach(([k,d]) => {
      const {pct,abs} = dyn(d.c, c.omsu[k]?.c||0);
      const ss = Object.entries(d.subs||{}).sort((a,b)=>b[1]-a[1]);
      entry.omsus.push({ name:k, count:d.c, dynPct:pct, dynAbs:abs,
        mainSub:ss[0]?.[0]||'-', mainSubCnt:ss[0]?.[1]||0,
        mainSubPct: d.c>0 ? Math.round((ss[0]?.[1]||0)/d.c*100) : 0 });
    });
    Object.entries(m.mails||{}).sort((a,b)=>b[1].c-a[1].c).forEach(([k,d]) => {
      entry.mails.push({ email:k, count:d.c, facts:Object.entries(d.facts||{}).sort((a,b)=>b[1]-a[1]), omsus:d.omsus||[] });
    });
    Object.entries(m.addrs||{}).sort((a,b)=>b[1].c-a[1].c).forEach(([k,d]) => {
      const ss = Object.entries(d.subs||{}).sort((a,b)=>b[1]-a[1]);
      entry.addrs.push({ address:k, count:d.c, mainSub:ss[0]?.[0]||'-',
        mainSubCnt:ss[0]?.[1]||0, mainSubPct: d.c>0?Math.round((ss[0]?.[1]||0)/d.c*100):0 });
    });
    result.push(entry);
  }
  return result.sort((a,b)=>b.total-a.total);
}
